apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-app
spec:
  replicas: 1
  # kubectl scale deployment health-app --replicas=1
  selector:
    matchLabels:
      app: health-app
  template:
    metadata:
      labels:
        app: health-app
    spec:
      containers:
        - name: health-app
          image: lotharthesavior/health-app:beta-15
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: health-app
spec:
  selector:
    app: health-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
